server: 
  port: 3344 
  
spring:
  application:
    name:  cloud-app-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:laoding/spring-cloud-config.git #GitHub上面的git仓库名字
 

